weights: results/train/drone/zjdet_unet/exp3/weights/best.pt
cfg: zjdet_u.yaml

data: drone.yaml
data_prefile: data_preprocess.yaml
hyp: hyp_v8.yaml
batch_size: 96 #128 # for 640*640 64
bgr: 1
conf_thresh: 0.1
last_conf: 0.3
verbose: True
visual_matched: False

div_area:
- 4
- 20
- 50
epochs: 500
patience: 300
rect: false
device: 4,5,6,7
world_size: 4
loss: LossV8
loss_supervision: 100

resume: True

imgsz:
- 180
- 240

#imgsz:
#- 88
#- 120
#train_cropped_imgsz: [180, 240]
#val_cropped_imgsz: [180, 240]
#slide_crop: False
#crop_sample_portion: 0.1
# origin_sample: 0.1
ignore_bkg: True
# pix_area : [2, 50]
# noautoanchor: True
# shuffle_epoch: 100
