weights: results/train/merge_scls/yolo_classify_s/exp/weights/best_precision.pt
cfg: configs/model/c3_classify_s.yaml
data: /home/workspace/zjdet/configs/data/merge_scls.yaml
data_prefile: data_preprocess.yaml
hyp: /home/workspace/zjdet/configs/hyp/hyp.yaml
project: /home/workspace/zjdet/results/train/merge_scls/c3_classify_s
save_dir: /home/workspace/zjdet/results/train/merge_scls/c3_classify_s/exp
epochs: 500
batch_size: 1024
bgr: 0
imgsz:
- 800
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 2
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 800
freeze: 0
task: 0
save_period: -1
save_warm: 0
val_first: false
div_area:
- 25
- 50
last_conf: 0.6
loss: ClassifyLoss
loss_supervision: 50
filter_str: ''
ignore_bkg: false
local_rank: -1
node: 0
addr: localhost
port: 23500
world_size: 8
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest

bkg_ratio: 1
train_obj_mask: 1
val_obj_mask: 0

