weights: results/train/merge_scls/squeezenet_big/exp2/weights/best_precision.pt  # checkpoints/squeezenet.pt
cfg: squeezenet_big.yaml
data: merge_scls.yaml
data_prefile: data_preprocess.yaml
hyp: hyp_slow.yaml
batch_size: 32
bgr: 0
last_conf: 0.6
verbose: True
visual_matched: True
imgsz:
- 256
div_area:
- 25
- 50
epochs: 1000
rect: false
world_size: 8
loss: ClassifyLoss
loss_supervision: 50
patience: 800
