weights:
- results/train/merge_scls/squeezenet/exp5/weights/best_precision.pt  #this means list
data: data/merge_scls.yaml
data_prefile: data_preprocess.yaml
batch_size: 128
bgr: 0
last_conf: [0.2, 0.3,0.4, 0.5, 0.6]
verbose: True

visual_matched: True
imgsz: [256, 256]
loss_num: 1
div_area:
- 25
- 50

bkg_ratio: 0
val_obj_mask: 0
#device: cpu