weights: results/train/drone/zjdet_unet/exp/weights/best.pt
cfg: zjdet_unet.yaml

data: drone.yaml
data_prefile: data_preprocess_false.yaml
hyp: hyp.yaml
batch_size: 4 #128 # for 640*640 64
bgr: 1
last_conf: 0.3
verbose: True
visual_matched: False

div_area:
- 5
- 10
- 50
epochs: 500
patience: 300
rect: false
world_size: 8
loss: LossV5
loss_supervision: 100


resume: False

imgsz:
- 544
- 960

#imgsz:
#- 88
#- 120
#train_cropped_imgsz: [180, 240]
#val_cropped_imgsz: [180, 240]
#slide_crop: False
#crop_sample_portion: 0.1
train_sample_portion: 0.1 # random select sample
val_sample_portion: .02 # random select sample
ignore_bkg: True
# pix_area : [2, 50]
# noautoanchor: True
# shuffle_epoch: 100