weights: results/train/drone/zjdet_neck/exp/weights/best.pt
cfg: zjdet_v8.yaml

data: drone.yaml
data_prefile: data_preprocess.yaml
hyp: hyp.yaml
batch_size: 64 # for 640*640 64
bgr: 1
last_conf: 0.3
verbose: True
visual_matched: False
imgsz:
- 540
- 960
div_area:
- 5
- 10
- 15
epochs: 1000
rect: false
world_size: 8
loss: LossV5
loss_supervision: 50
patience: 500

resume: False
#train_cropped_imgsz: [540, 960]
#val_cropped_imgsz: [540, 960]
#slide_crop: True
train_sample_portion: 0.8 # random select sample
val_sample_portion: .2 # random select sample
ignore_bkg: True
# find_unused_parameters: True