weights: results/train/drone/zjdet_unet/exp3/weights/best.pt
cfg: zjdet_unet.yaml

data: drone.yaml
data_prefile: data_preprocess.yaml
hyp: hyp_v8.yaml
batch_size: 16 #128 # for 640*640 64
bgr: 1
conf_thresh: 0.1
last_conf: 0.3
verbose: True
visual_matched: False

div_area:
- 4
- 20
- 50
epochs: 500
patience: 300
rect: false
world_size: 8
loss: LossV8
loss_supervision: 100


resume: False

imgsz:
- 180
- 240

#imgsz:
#- 88
#- 120
#train_cropped_imgsz: [180, 240]
#val_cropped_imgsz: [180, 240]
#slide_crop: False
#crop_sample_portion: 0.1
# origin_sample: 0.1
train_sample_portion: 0.8 # random select sample
val_sample_portion: .2 # random select sample
ignore_bkg: True
# pix_area : [2, 50]
# noautoanchor: True
# shuffle_epoch: 100