weights: results/train/merge_scls/squeezenet_big/exp2/weights/best_precision.pt  # checkpoints/squeezenet.pt
cfg: squeezenet_sppf_fpn.yaml
data: merge_scls.yaml
data_prefile: data_preprocess.yaml
hyp: hyp.yaml
batch_size: 128
bgr: 0
last_conf: 0.6
verbose: True
visual_matched: False
imgsz:
- 256
div_area:
- 25
- 50
epochs: 1000
rect: false
world_size: 8
loss: ObjClassifyLoss
loss_supervision: 50
patience: 800
