weights: results/train/drone/zjdet_v8s/exp/weights/best.pt
cfg: zjdet_v8s.yaml

data: drone.yaml
data_prefile: data_preprocess.yaml
hyp: hyp.yaml
batch_size: 32 # for 640*640 64
bgr: 1
conf_thresh: 0.1
last_conf: 0.3
verbose: True
visual_matched: False
imgsz:
- 540
- 960
div_area:
- 5
- 10
- 15
epochs: 1000
rect: false
device: 0,1,2,3
world_size: 4
loss: LossV5
loss_supervision: 50
patience: 300

resume: False
#train_cropped_imgsz: [540, 960]
#val_cropped_imgsz: [540, 960]
#slide_crop: True
train_sample_portion: 0.8 # random select sample
val_sample_portion: .2 # random select sample
ignore_bkg: True
# find_unused_parameters: True