weights: checkpoints/zjdet_neck_merge_19_2G_71_89_over25_78_93.pt
cfg: zjdet_neck.yaml

data: dota.yaml
data_prefile: data_preprocess.yaml
hyp: hyp.yaml
batch_size: 256
bgr: 1
last_conf: 0.6
verbose: True
visual_matched: False
imgsz:
- 640
div_area:
- 10
- 15
epochs: 1000
rect: false
world_size: 8
loss: LossV5
loss_supervision: 50
patience: 800

resume: False
train_cropped_imgsz: [832, 832]
val_cropped_imgsz: [832, 832]
# device: 0,1