#                 from  n    params  module                                  arguments
#  0                -1      9536  models.layers.common_layer.ReluConv     [3, 64, 7, 2, 3]
#  1                -1         0  torch.nn.modules.pooling.MaxPool2d      [3, 2, 1]
#  2                -1    221952  models.layers.resnet_layer.Repeat_BasicBlock[64, 64, 3, 3, 1, 1]
#  3                -1    230144  models.layers.resnet_layer.BasicBlock   [64, 128, 3, 2, 1]
#  4                -1    886272  models.layers.resnet_layer.Repeat_BasicBlock[128, 128, 3, 3, 1, 1]
#  5                -1    919040  models.layers.resnet_layer.BasicBlock   [128, 256, 3, 2, 1]
#  6                -1   5903360  models.layers.resnet_layer.Repeat_BasicBlock[256, 256, 5, 3, 1, 1]
#  7                -1   3673088  models.layers.resnet_layer.BasicBlock   [256, 512, 3, 2, 1]
#  8                -1   9441280  models.layers.resnet_layer.Repeat_BasicBlock[512, 512, 2, 3, 1, 1]
#  9                -1       513  models.head.Flatten                     [512, 1]
#Model Summary: 207layers, 21285185 parameters, 21285185 gradients,image size is (640, 640), 60.1 GFLOPs in cpu
# time (ms)     GFLOPs     params                                    module                       input_size
#     18.22     1.9792       9536  models.layers.common_layer.ReluConv       torch.Size([1, 3, 640, 640])
#      7.72     0.0000          0  torch.nn.modules.pooling.MaxPool2d        torch.Size([1, 64, 320, 320])
#     47.84    11.4033     221952  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 64, 160, 160])
#     14.16     2.9557     230144  models.layers.resnet_layer.BasicBlock     torch.Size([1, 64, 160, 160])
#     36.09    11.3639     886272  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 128, 80, 80])
#     10.90     2.9458     919040  models.layers.resnet_layer.BasicBlock     torch.Size([1, 128, 80, 80])
#     52.34    18.9071    5903360  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 256, 40, 40])
#      9.47     2.9409    3673088  models.layers.resnet_layer.BasicBlock     torch.Size([1, 256, 40, 40])
#     21.04     7.5563    9441280  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 512, 20, 20])
#      0.07     0.0004        513  models.head.Flatten                       torch.Size([1, 512, 20, 20])
#    217.86    60.0527   21285185  Total use cpu
#    217.86    60.0527   21285185  Per image use cpu

#  0                -1      3264  models.layers.common_layer.ReluConv     [1, 64, 7, 2, 3]
#  1                -1         0  torch.nn.modules.pooling.MaxPool2d      [3, 2, 1]
#  2                -1    221952  models.layers.resnet_layer.Repeat_BasicBlock[64, 64, 3, 3, 1, 1]
#  3                -1    230144  models.layers.resnet_layer.BasicBlock   [64, 128, 3, 2, 1]
#  4                -1    886272  models.layers.resnet_layer.Repeat_BasicBlock[128, 128, 3, 3, 1, 1]
#  5                -1    919040  models.layers.resnet_layer.BasicBlock   [128, 256, 3, 2, 1]
#  6                -1   5903360  models.layers.resnet_layer.Repeat_BasicBlock[256, 256, 5, 3, 1, 1]
#  7                -1   3673088  models.layers.resnet_layer.BasicBlock   [256, 512, 3, 2, 1]
#  8                -1   9441280  models.layers.resnet_layer.Repeat_BasicBlock[512, 512, 2, 3, 1, 1]
#  9                -1       513  models.head.Flatten                     [512, 1]
#Model Summary: 207layers, 21278913 parameters, 21278913 gradients,image size is (640, 640), 58.8 GFLOPs in cpu
# time (ms)     GFLOPs     params                                    module                       input_size
#      1.88     0.0734       3264  models.layers.common_layer.ReluConv       torch.Size([1, 1, 208, 208])
#      0.81     0.0000          0  torch.nn.modules.pooling.MaxPool2d        torch.Size([1, 64, 104, 104])
#      4.11     1.2045     221952  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 64, 52, 52])
#      1.36     0.3122     230144  models.layers.resnet_layer.BasicBlock     torch.Size([1, 64, 52, 52])
#      3.57     1.2003     886272  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 128, 26, 26])
#      1.82     0.3112     919040  models.layers.resnet_layer.BasicBlock     torch.Size([1, 128, 26, 26])
#     10.55     1.9971    5903360  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 256, 13, 13])
#      3.71     0.3603    3673088  models.layers.resnet_layer.BasicBlock     torch.Size([1, 256, 13, 13])
#      9.19     0.9256    9441280  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 512, 7, 7])
#      0.10     0.0001        513  models.head.Flatten                       torch.Size([1, 512, 7, 7])
#     37.09     6.3845   21278913  Total use cpu
#     37.09     6.3845   21278913  Per image use cpu
# Parameters
depth_multiple: 1.  # model depth multiple
width_multiple: 1.  # layer channel multiple
depth_layer: [Repeat_BasicBlock]
width_layer: [ReluConv, BasicBlock, Repeat_BasicBlock, Flatten]
nc: 80
backbone:
  [[-1, ReluConv, [64, 7, 2, 3]],  #
   [-1, nn.MaxPool2d, [3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [64, 64, 3, 3, 1, 1]],  #
   [-1, BasicBlock, [64, 128, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [128, 128, 3, 3, 1, 1]],  #
   [-1, BasicBlock, [128, 256, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [256, 256, 5, 3, 1, 1]],  #
   [-1, BasicBlock, [256, 512, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [512, 512, 2, 3, 1, 1]],  #
  ]

neck:
  []
head:
  [[-1, Flatten, [512, nc]],  # Detect(P3, P4, P5)
  ]

