#                 from  n    params  module                                  arguments
#  0                -1      3264  models.layers.common_layer.ReluConv     [1, 64, 7, 2, 3]
#  1                -1         0  torch.nn.modules.pooling.MaxPool2d      [3, 2, 1]
#  2                -1    147968  models.layers.resnet_layer.Repeat_BasicBlock[64, 64, 2, 3, 1, 1]
#  3                -1    230144  models.layers.resnet_layer.BasicBlock   [64, 128, 3, 2, 1]
#  4                -1    295424  models.layers.resnet_layer.Repeat_BasicBlock[128, 128, 1, 3, 1, 1]
#  5                -1    919040  models.layers.resnet_layer.BasicBlock   [128, 256, 3, 2, 1]
#  6                -1   1180672  models.layers.resnet_layer.Repeat_BasicBlock[256, 256, 1, 3, 1, 1]
#  7                -1   3673088  models.layers.resnet_layer.BasicBlock   [256, 512, 3, 2, 1]
#  8                -1   4720640  models.layers.resnet_layer.Repeat_BasicBlock[512, 512, 1, 3, 1, 1]
#  9                -1       513  models.head.Flatten                     [512, 1]
#Model Summary: 119layers, 11170753 parameters, 11170753 gradients,image size is (640, 640), 28.5 GFLOPs in cpu
# time (ms)     GFLOPs     params                                    module                       input_size
#      1.87     0.0734       3264  models.layers.common_layer.ReluConv       torch.Size([1, 1, 208, 208])
#      0.83     0.0000          0  torch.nn.modules.pooling.MaxPool2d        torch.Size([1, 64, 104, 104])
#      2.53     0.8030     147968  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 64, 52, 52])
#      1.32     0.3122     230144  models.layers.resnet_layer.BasicBlock     torch.Size([1, 64, 52, 52])
#      1.19     0.4001     295424  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 128, 26, 26])
#      1.74     0.3112     919040  models.layers.resnet_layer.BasicBlock     torch.Size([1, 128, 26, 26])
#      1.94     0.3994    1180672  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 256, 13, 13])
#      3.54     0.3603    3673088  models.layers.resnet_layer.BasicBlock     torch.Size([1, 256, 13, 13])
#      4.41     0.4628    4720640  models.layers.resnet_layer.Repeat_BasicBlock  torch.Size([1, 512, 7, 7])
#      0.08     0.0001        513  models.head.Flatten                       torch.Size([1, 512, 7, 7])
#     19.44     3.1224   11170753  Total use cpu
#     19.44     3.1224   11170753  Per image use cpu
# Parameters
depth_multiple: 1.  # model depth multiple
width_multiple: 1.  # layer channel multiple
depth_layer: [Repeat_BasicBlock]
width_layer: [ReluConv, BasicBlock, Repeat_BasicBlock, Flatten]
nc: 80
backbone:
  [[-1, ReluConv, [64, 7, 2, 3]],  #
   [-1, nn.MaxPool2d, [3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [64, 64, 2, 3, 1, 1]],  #
   [-1, BasicBlock, [64, 128, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [128, 128, 1, 3, 1, 1]],  #
   [-1, BasicBlock, [128, 256, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [256, 256, 1, 3, 1, 1]],  #
   [-1, BasicBlock, [256, 512, 3, 2, 1]],  #
   [-1, Repeat_BasicBlock, [512, 512, 1, 3, 1, 1]],  #
  ]

neck:
  []
head:
  [[-1, Flatten, [512, nc]],  # Detect(P3, P4, P5)
  ]

