#                 from  n    params  module                                  arguments
#  0                -1      1760  models.layers.common_layer.Conv         [3, 16, 6, 2, 2]
#  1                -1      4672  models.layers.common_layer.Conv         [16, 32, 3, 2]
#  2                -1      4800  models.layers.yolo_layer.C3             [32, 32, 1]
#  3                -1     18560  models.layers.common_layer.Conv         [32, 64, 3, 2]
#  4                -1     29184  models.layers.yolo_layer.C3             [64, 64, 2]
#  5                -1     73984  models.layers.common_layer.Conv         [64, 128, 3, 2]
#  6                -1    156928  models.layers.yolo_layer.C3             [128, 128, 3]
#  7                -1    147712  models.layers.common_layer.Conv         [128, 128, 3, 2]
#  8                -1     74496  models.layers.yolo_layer.C3             [128, 128, 1]
#  9                 6     41344  models.layers.yolo_layer.SPPF           [128, 128, 5]
# 10                -1      8320  models.layers.common_layer.Conv         [128, 64, 1, 1]
# 11                -1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
# 12           [-1, 4]         0  models.layers.common_layer.Concat       [1]
# 13                -1     22912  models.layers.yolo_layer.C3             [128, 64, 1, False]
# 14                -1     36992  models.layers.common_layer.Conv         [64, 64, 3, 2]
# 15          [-1, 10]         0  models.layers.common_layer.Concat       [1]
# 16                -1     74496  models.layers.yolo_layer.C3             [128, 128, 1, False]
# 17                -1    147712  models.layers.common_layer.Conv         [128, 128, 3, 2]
# 18           [-1, 8]         0  models.layers.common_layer.Concat       [1]
# 19                -1    296448  models.layers.yolo_layer.C3             [256, 256, 1, False]
# 20      [13, 16, 19]    115005  models.head.Detect                      [[64, 128, 256], 80, [[8, 15, 18, 30, 25, 15], [32, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]]]
#Model Summary: 241layers, 1255325 parameters, 1255325 gradients,image size is 640, 3.9 GFLOPs in cpu
# time (ms)     GFLOPs     params                                    module                       input_size
#      6.85     2.9360       1760  models.layers.common_layer.Conv           torch.Size([8, 3, 640, 640])
#      0.50     1.9399       4672  models.layers.common_layer.Conv           torch.Size([8, 16, 320, 320])
#      1.80     2.0447       4800  models.layers.yolo_layer.C3               torch.Size([8, 32, 160, 160])
#      0.40     1.9137      18560  models.layers.common_layer.Conv           torch.Size([8, 32, 160, 160])
#      1.40     3.0409      29184  models.layers.yolo_layer.C3               torch.Size([8, 64, 80, 80])
#      0.30     1.9005      73984  models.layers.common_layer.Conv           torch.Size([8, 64, 80, 80])
#      1.90     4.0501     156928  models.layers.yolo_layer.C3               torch.Size([8, 128, 40, 40])
#      0.20     0.9470     147712  models.layers.common_layer.Conv           torch.Size([8, 128, 40, 40])
#      0.90     0.4817      74496  models.layers.yolo_layer.C3               torch.Size([8, 128, 20, 20])
#      0.50     1.0682      41344  models.layers.yolo_layer.SPPF             torch.Size([8, 128, 40, 40])
#      0.20     0.2163       8320  models.layers.common_layer.Conv           torch.Size([8, 128, 40, 40])
#      0.10     0.0066          0  torch.nn.modules.upsampling.Upsample      torch.Size([8, 64, 40, 40])
#      0.10     0.0000          0  models.layers.common_layer.Concat         [torch.Size([8, 64, 80, 80]), torch.Size([8, 64, 80, 80])]
#      1.10     2.3855      22912  models.layers.yolo_layer.C3               torch.Size([8, 128, 80, 80])
#      0.30     0.9503      36992  models.layers.common_layer.Conv           torch.Size([8, 64, 80, 80])
#      0.00     0.0000          0  models.layers.common_layer.Concat         [torch.Size([8, 64, 40, 40]), torch.Size([8, 64, 40, 40])]
#      1.10     1.9268      74496  models.layers.yolo_layer.C3               torch.Size([8, 128, 40, 40])
#      0.20     0.9470     147712  models.layers.common_layer.Conv           torch.Size([8, 128, 40, 40])
#      0.00     0.0000          0  models.layers.common_layer.Concat         [torch.Size([8, 128, 20, 20]), torch.Size([8, 128, 20, 20])]
#      1.00     1.9071     296448  models.layers.yolo_layer.C3               torch.Size([8, 256, 20, 20])
#      0.70     2.9245     115005  models.head.Detect                        [torch.Size([8, 64, 80, 80]), torch.Size([8, 128, 40, 40]), torch.Size([8, 256, 20, 20])]
#     19.55    31.5867    1255325  Total
# Parameters
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple
depth_layer: [C3]
width_layer: [Conv, C3, SPPF, Detect]
anchors:
  - [8,15, 18,30, 25,15]  # P3/8
  - [32,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# [from,  module, args], args=[ch_in , ch_out, etc]
backbone:
  [[-1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, Conv, [64, 128, 3, 2]],  # 1-P2/4
   [-1, C3, [128, 128, 3]],
   [-1, Conv, [128, 256, 3, 2]],  # 3-P3/8
   [-1, C3, [256, 256, 6]],
   [-1, Conv, [256, 512, 3, 2]],  # 5-P4/16
   [-1, C3, [512, 512, 9]],
   [-1, Conv, [512, 512, 3, 2]], # 7-P5/32
   [-1, C3, [512, 512, 3]],
   [6, SPPF, [512, 512, 5]],  # 9
  ]

neck:
  [[-1, Conv, [512, 256, 1, 1]],
   [-1, nn.Upsample,  [None, 2, 'nearest']],
   [[-1, 4], Concat,  [1]],  # cat backbone P3/8-small
   [-1, C3, [512, 256, 3,  False]], #13

   [-1, Conv, [256, 256, 3, 2]],
   [[-1, 10], Concat,  [1]],  # cat head P5
   [-1, C3, [512, 512, 3, False]],  # 16 (P4/16-medium)

   [-1, Conv, [512, 512, 3, 2]],
   [[-1, 8], Concat,  [1]],  # cat head P5
   [-1, C3, [1024, 1024, 3, False]],  # 19 (P5/32-big)
  ]

head:
  [[[13, 16, 19], Detect, [[256, 512, 1024], nc, anchors]], # Detect(P3, P4, P5)
  ]

